print("Greetings!")
print("Word on the street is you are in need of a band name")
input()
print("You are in luck because I can create Awesome Band Names.")
input()
print("First things first, What is your mothers maiden name?")
mothersName = input()
print("Just planning, I can't believe you told me " + mothersName)
input()
print("I'll keep that a seceret sshhhh ")
input()
print("Okay, here's the real question")
print("Where's the scariest place you can think of?")
Location = input()
print(Location + " That is a messed up place\n you might need to go see a doctor")
print("Okay second question")
print("What is your favorite animal?")
animal = input()
print("Thanks for the information a great band name would be...")
input()
print(Location + " " + animal)